spring.application.name=OTN_app

password.hash.code=SHA-256

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/teamdev
spring.datasource.username=postgres
spring.datasource.password=Yuhei11N10
spring.jpa.open-in-view=True