package com.example.demo.entity;

import java.util.Date;

public class Introductions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.introduction_id
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private Integer introduction_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.user_id
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.name
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.kana
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private String kana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.gender
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.hobby
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.word
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.team_name
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private String team_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.created_at
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.updated_at
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    private Date updated_at;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.introduction_id
     *
     * @return the value of public.introductions.introduction_id
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public Integer getIntroduction_id() {
        return introduction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.introduction_id
     *
     * @param introduction_id the value for public.introductions.introduction_id
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setIntroduction_id(Integer introduction_id) {
        this.introduction_id = introduction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.user_id
     *
     * @return the value of public.introductions.user_id
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.user_id
     *
     * @param user_id the value for public.introductions.user_id
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.name
     *
     * @return the value of public.introductions.name
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.name
     *
     * @param name the value for public.introductions.name
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.kana
     *
     * @return the value of public.introductions.kana
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public String getKana() {
        return kana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.kana
     *
     * @param kana the value for public.introductions.kana
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setKana(String kana) {
        this.kana = kana == null ? null : kana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.gender
     *
     * @return the value of public.introductions.gender
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.gender
     *
     * @param gender the value for public.introductions.gender
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.hobby
     *
     * @return the value of public.introductions.hobby
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.hobby
     *
     * @param hobby the value for public.introductions.hobby
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.word
     *
     * @return the value of public.introductions.word
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.word
     *
     * @param word the value for public.introductions.word
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.team_name
     *
     * @return the value of public.introductions.team_name
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public String getTeam_name() {
        return team_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.team_name
     *
     * @param team_name the value for public.introductions.team_name
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setTeam_name(String team_name) {
        this.team_name = team_name == null ? null : team_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.created_at
     *
     * @return the value of public.introductions.created_at
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.created_at
     *
     * @param created_at the value for public.introductions.created_at
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.updated_at
     *
     * @return the value of public.introductions.updated_at
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.updated_at
     *
     * @param updated_at the value for public.introductions.updated_at
     *
     * @mbg.generated Thu Apr 17 22:03:26 JST 2025
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }
}